server:
  port: 9003

spring:
  application:
    name: FILEMANAGER-SERVICE
  config:
    import: optional:configserver:http://${CNF}:9296/
  datasource:
    url: jdbc:postgresql://${PGIP}:5432/postgres
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB